docs/index.md
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/AgpVersionHandler.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/InferAndroidTestKeepRules.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperExtension.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt
sample/build.gradle

This is the finishing touches on the API of the plugin. With this, the plugin is no longer ordering dependent and requires no configuration by default.
In fact - the only configuration remaining after this is just r8 controls, which have been tweaked to be a little more conventional.
Resolves #5 
Resolves #2

Simplify defaults and cleanup setups

---

docs/configuration.md
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperExtension.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt
sample/build.gradle

Resolves #15 
Now you can do something like this to explicitly filter out certain variants
```gradle
keeper {
variantFilter {
setIgnored(name == "variantThatShouldTotallyBeIgnored")
}
}
```
~~This works based on eyeballing, now just need to add a test to lock it down~~

Add variant filtering

---

docs/configuration.md
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/InferAndroidTestKeepRules.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperExtension.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt

Add R8 repo management opt out

---

.github/workflows/ci.yml
build.gradle
docs/index.md
keeper-gradle-plugin/build.gradle.kts
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/AgpVersionHandler.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt

We may add 3.5.x support again, but only as a recipe for a service loader approach if we get feedback asking for it. This also lets us add back 4.x betas to the test matrix

Move to AGP 3.6.0 stable + remove 3.5.x support

---

keeper-gradle-plugin/build.gradle.kts
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/InferAndroidTestKeepRules.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/ZipFlingerExt.kt
publish.sh

Resolves #20 
Perf comparisons on the slack app:
| Task | Before | After |
|-|--------|-------|
| inferExternalStagingAndroidTestKeepRulesForKeeper | 14.126s | 11.138s |
| jarExternalStagingClassesForKeeper | 10.364s | 6.347s |
| jarExternalStagingAndroidTestClassesForKeeper | 4.504s | 2.609s |
~~Will do some perf comparisons in our app and report the findings here~~
~~**On hold as ZipFlinger fails explosively when there are colliding names:** https://issuetracker.google.com/issues/150320652~~

Switch to Zipflinger

---

keeper-gradle-plugin/build.gradle.kts

This has a fix for gradle plugin uploads that was used for our 0.3.1 upload

Update maven publish plugin to 0.11.1

---

keeper-gradle-plugin/build.gradle.kts

The first time I ran the `test` task against the plugin, it seemed like it was hanging and I ctrl-c'd. Eventually I figured out they were just very slow tests (the functional tests). I use this approach in [my own project](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin) so I can keep tabs on progress.
Output looks like:
```
> Task :test
Running test: Test variantFilter[R8](com.slack.keeper.KeeperFunctionalTest)
Running test: Test variantFilterWarning[R8](com.slack.keeper.KeeperFunctionalTest)
Running test: Test standard[R8](com.slack.keeper.KeeperFunctionalTest)
Running test: Test manualR8RepoManagement[R8](com.slack.keeper.KeeperFunctionalTest)
Running test: Test variantFilter[PROGUARD](com.slack.keeper.KeeperFunctionalTest)
Running test: Test …
```

Log test methods for faster feedback.

---

.github/workflows/ci.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
keeper-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/AgpVersionHandler.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/InferAndroidTestKeepRules.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperExtension.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt
sample/build.gradle

AGP 4 uses a different `android-classes-jar` attribute value for artifact viewing
Resolves #45

Support AGP 4

---

keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/ZipFlingerExt.kt

Nice little optimization by reusing the previous task's output. This, I think, allows changing the app classpath in a compatible way without making the test jar  bundling out of date

More diagnostic info + only process app artifacts once

---

docs/configuration.md
keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt

As reported in #60, the behavior of the variantFilter does not match the documentation.
This PR sets a better default by disabling Keeper for all variants where minifyEnabled = false.
It also uses ignored = false as the default when a user does specify a variantFilter which says nothing about the current variant. This matches the current documentation.
I hope you can agree that this behavior is preferable.

Make the default behavior to ignore minifyEnabled = false variants

---

keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt

#61 changed how we configure which variants keeper runs on, adding better defaults. This PR updates the functional tests to handle a few more cases, and adds back in a test case that checks the presence of the warning logged when keeper is configured to run for a non-minified build variant (using `setIgnore(false)` in a `variantFilter`).

Re-work variantFilter in functional tests to cover more cases

---

.github/workflows/ci.yml

gradle -p is allowing to run commands with a custom project path, here the plugin subproject only.

Simplify plugin tests execution

---

keeper-gradle-plugin/src/main/java/com/slack/keeper/InferAndroidTestKeepRules.kt
keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperExtension.kt
keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt
sample/build.gradle
sample/expectedRules.pro

This is based on a conversation I had with the R8 team in [this ticket](https://issuetracker.google.com/issues/173435379).
By using this new experimental entry-point, I could solve my rules generation issues and start running my instrumented tests with keeper support.
As you can notice several arguments changed (like --keeprules to --keep-rules) and even for the keeper sample app, I had to rely on "--map-diagnostics:MissingDefinitionsDiagnostic error info" even if I'm not sure it should be used by default or not...
Anyway I hope by opening this PR to facilitate the migration to this new command when @ZacSweers will judge it's the good time to do it 👍

Add support for the new TraceReferences entry-point

---

.github/workflows/ci.yml
.github/workflows/run_instrumentation_tests.sh
keeper-gradle-plugin/src/main/java/com/slack/keeper/InferAndroidTestKeepRules.kt
sample/build.gradle

Followups from #69 (CC @pgreze)
* Use lazy `mainClass` property
* Wire into CI for the sample too

TraceReferences followups

---

docs/configuration.md
keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperExtension.kt
keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt
sample/src/main/kotlin/com/slack/keeper/sample/SampleApplication.java

See the configuration.md file and doc on `configureL8` function for full details!
Also resolves #67, which is a nice added layer of validation.

Complete L8 support

---

keeper-gradle-plugin/api/keeper-gradle-plugin.api
keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/main/java/com/slack/keeper/VariantClasspathJar.kt

Gradle's `@Classpath` annotation seems quite strange and turns out is not actually what we want. This reworks things to explicitly use `ArtifactCollection` + absolute paths for caching. This is important because we care about the jar locations even if the contents are the same because we need to read their contents during task exec. This is a nicer solution than just disabling caching entirely as it will still allow caching on the same machine.

Rework artifact inputs

---

.github/workflows/ci.yml

The AdoptOpenJDK has been discontinued since July 2021 (https://adoptopenjdk.net). Switching the distribution to Azul Zulu. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK. 
Please see more details at Foojay.io:
https://foojay.io/today/github-actions-with-java-part-2/

Using TCK Tested JDK builds of OpenJDK  in GH actions

---

keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt

Tested with `./gradlew build` 
`Contributing` doc mention signing CLA: https://slackhq.github.io/keeper/contributing/#requirements
but the link doesn't work:

Update default R8 to 8.2.38

---

keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt

This adds a potential workaround for #135 by taking advantage of the configuration split for `disableTestProguardFiles`.
I don't think the main configuration has to wait for `afterEvaluate` - it wasn't in `afterEvaluate` [prior to](https://github.com/slackhq/keeper/pull/117/files#diff-97986db993489fce0231211149a4abef24deae6c53cea6f6e422434faaebc849L281) #117, so maybe we can move that part out of `afterEvaluate` to avoid running into the `disallowChanges` issue.
If `disableTestProguardFiles` is not `true`, then the new `disallowChanges()` will still cause the #135 issue, but on the latest AGP versions not specifying `disableTestProguardFiles` won't work anyway.
I validated this change locally against https://github.com/alexvanyo/composelife/pull/1500 updating `8.4.0-alpha04` to …

Workaround disallow changes by splitting configuration file setup

---

build.gradle.kts
keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/Files.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt

Try updating to fix main more

---

.github/workflows/ci.yml
keeper-gradle-plugin/src/main/java/com/slack/keeper/ZipFlingerExt.kt
keeper-gradle-plugin/src/test/kotlin/com/slack/keeper/KeeperFunctionalTest.kt

This PR should supercede both of these:
- Closes #147 (that one was missing some test fixes which caused failures on windows)
- Closes #148 (that one is actually the same as the first three commits here, but this PR lets you see everything in action)
I developed this on my fork with the patch from @voczi from #147 as a starting point, picked into a branch where I worked on the workflow.
I made a PR into my fork's main branch to run CI (over and over and over) until I was sure I had it working
Test run showing success: https://github.com/mikehardy/keeper/actions/runs/9686107630
There is nothing fancy about the windows fix itself, it's standard `Path.separator()` and `System.lineSeparator()` stuff - exactly as you would expect
There are two fancy things about the workflow / test fixes:
- …

Multiplatform worfklow with windows fix
